## I Dataset: crx.data

In [1]:
import pandas as pd
import numpy as np

#load Data
data=pd.read_csv('crx.data', header=None)

In [2]:
data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

### In the dataset crx.data, name the columns as col1, col2..col16

In [3]:
col_names =['Col'+str(s) for s in range(1,17)]
data.columns =col_names
data.head()

Col1   Col2   Col3 Col4 Col5 Col6 Col7  Col8 Col9 Col10  Col11 Col12 Col13  \
0    b  30.83  0.000    u    g    w    v  1.25    t     t      1     f     g   
1    a  58.67  4.460    u    g    q    h  3.04    t     t      6     f     g   
2    a  24.50  0.500    u    g    q    h  1.50    t     f      0     f     g   
3    b  27.83  1.540    u    g    w    v  3.75    t     t      5     t     g   
4    b  20.17  5.625    u    g    w    v  1.71    t     f      0     f     s   

   Col14  Col15 Col16  
0  00202      0     +  
1  00043    560     +  
2  00280    824     +  
3  00100      3     +  
4  00120      0     +

### Print the last 10 rows of data

In [4]:
data.tail(10)

Col1   Col2    Col3 Col4 Col5 Col6 Col7   Col8 Col9 Col10  Col11 Col12  \
680    b  19.50   0.290    u    g    k    v  0.290    f     f      0     f   
681    b  27.83   1.000    y    p    d    h  3.000    f     f      0     f   
682    b  17.08   3.290    u    g    i    v  0.335    f     f      0     t   
683    b  36.42   0.750    y    p    d    v  0.585    f     f      0     f   
684    b  40.58   3.290    u    g    m    v  3.500    f     f      0     t   
685    b  21.08  10.085    y    p    e    h  1.250    f     f      0     f   
686    a  22.67   0.750    u    g    c    v  2.000    f     t      2     t   
687    a  25.25  13.500    y    p   ff   ff  2.000    f     t      1     t   
688    b  17.92   0.205    u    g   aa    v  0.040    f     f      0     f   
689    b  35.00   3.375    u    g    c    h  8.290    f     f      0     t   

    Col13  Col14  Col15 Col16  
680     g  00280    364     -  
681     g  00176    537     -  
682     g  00140      2     -  
683     g  00240      3     -  
684     s  00400      0     -  
685     g  00260      0     -  
686     g  00200    394     -  
687     g  00200      1     -  
688     g  00280    750     -  
689     g  00000      0     -

### Replace the ‘?’ with Not-a-Number

In [7]:
data=data.replace('?',np.nan)
data.head()

Col1   Col2   Col3 Col4 Col5 Col6 Col7  Col8 Col9 Col10  Col11 Col12 Col13  \
0    b  30.83  0.000    u    g    w    v  1.25    t     t      1     f     g   
1    a  58.67  4.460    u    g    q    h  3.04    t     t      6     f     g   
2    a  24.50  0.500    u    g    q    h  1.50    t     f      0     f     g   
3    b  27.83  1.540    u    g    w    v  3.75    t     t      5     t     g   
4    b  20.17  5.625    u    g    w    v  1.71    t     f      0     f     s   

   Col14  Col15 Col16  
0  00202      0     +  
1  00043    560     +  
2  00280    824     +  
3  00100      3     +  
4  00120      0     +

### Comment on the datatype of variables

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    678 non-null    object 
 1   Col2    678 non-null    object 
 2   Col3    690 non-null    float64
 3   Col4    684 non-null    object 
 4   Col5    684 non-null    object 
 5   Col6    681 non-null    object 
 6   Col7    681 non-null    object 
 7   Col8    690 non-null    float64
 8   Col9    690 non-null    object 
 9   Col10   690 non-null    object 
 10  Col11   690 non-null    int64  
 11  Col12   690 non-null    object 
 12  Col13   690 non-null    object 
 13  Col14   677 non-null    object 
 14  Col15   690 non-null    int64  
 15  Col16   690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


### The col16 has + and -, replace them ‘P’ and ‘N’ respectively

In [10]:
data['Col16']=data['Col16'].map({'+':'P', '-':'N'})
data.head()

Col1   Col2   Col3 Col4 Col5 Col6 Col7  Col8 Col9 Col10  Col11 Col12 Col13  \
0    b  30.83  0.000    u    g    w    v  1.25    t     t      1     f     g   
1    a  58.67  4.460    u    g    q    h  3.04    t     t      6     f     g   
2    a  24.50  0.500    u    g    q    h  1.50    t     f      0     f     g   
3    b  27.83  1.540    u    g    w    v  3.75    t     t      5     t     g   
4    b  20.17  5.625    u    g    w    v  1.71    t     f      0     f     s   

   Col14  Col15 Col16  
0  00202      0     P  
1  00043    560     P  
2  00280    824     P  
3  00100      3     P  
4  00120      0     P

In [11]:
data.tail()

Col1   Col2    Col3 Col4 Col5 Col6 Col7  Col8 Col9 Col10  Col11 Col12  \
685    b  21.08  10.085    y    p    e    h  1.25    f     f      0     f   
686    a  22.67   0.750    u    g    c    v  2.00    f     t      2     t   
687    a  25.25  13.500    y    p   ff   ff  2.00    f     t      1     t   
688    b  17.92   0.205    u    g   aa    v  0.04    f     f      0     f   
689    b  35.00   3.375    u    g    c    h  8.29    f     f      0     t   

    Col13  Col14  Col15 Col16  
685     g  00260      0     N  
686     g  00200    394     N  
687     g  00200      1     N  
688     g  00280    750     N  
689     g  00000      0     N

### Find and display the number of variables of type ‘Object’

In [13]:
obj_columns=[c for c in data.columns if data[c].dtypes=='O']
data[obj_columns].head()

Col1   Col2 Col4 Col5 Col6 Col7 Col9 Col10 Col12 Col13  Col14 Col16
0    b  30.83    u    g    w    v    t     t     f     g  00202     P
1    a  58.67    u    g    q    h    t     t     f     g  00043     P
2    a  24.50    u    g    q    h    t     f     f     g  00280     P
3    b  27.83    u    g    w    v    t     t     t     g  00100     P
4    b  20.17    u    g    w    v    t     f     f     s  00120     P

In [35]:
print(len(obj_columns))

12


## II Dataset: loan.csv

In [14]:
df=pd.read_csv('loan.csv')

In [15]:
df.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder    income date_issued  target        loan_purpose  \
0        RENT   84600.0  2013-06-11       0  Debt consolidation   
1       OWNER  102000.0  2014-05-08       0        Car purchase   
2        RENT   69840.0  2013-10-26       0  Debt consolidation   
3        RENT  100386.0  2015-08-20       0  Debt consolidation   
4        RENT   95040.0  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  
0                   4.0        2016-01-14                     NaN  
1                  13.0        2016-01-25                     NaN  
2                   8.0        2014-09-26                     NaN  
3                  20.0        2016-01-26                     NaN  
4                  14.0        2016-01-11                     NaN

### Display the mean of any two variables with continuous values


In [16]:
interest_mean = df["interest"].mean()
income_mean = df["income"].mean()
print("Mean Interest is: ", interest_mean)
print("Mean Income is: ", income_mean)

Mean Interest is:  12.678819440000039
Mean Income is:  71572.28728914999


### Print the number of discrete variables

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   customer_id             10000 non-null  int64  
 1   disbursed_amount        10000 non-null  float64
 2   interest                10000 non-null  float64
 3   market                  10000 non-null  object 
 4   employment              9389 non-null   object 
 5   time_employed           9471 non-null   object 
 6   householder             10000 non-null  object 
 7   income                  10000 non-null  float64
 8   date_issued             10000 non-null  object 
 9   target                  10000 non-null  int64  
 10  loan_purpose            10000 non-null  object 
 11  number_open_accounts    10000 non-null  float64
 12  date_last_payment       10000 non-null  object 
 13  number_credit_lines_12  238 non-null    float64
dtypes: float64(5), int64(2), object(7)
memo

In [19]:
df['customer_id'].head()

0    0
1    1
2    2
3    3
4    4
Name: customer_id, dtype: int64

In [20]:
df['number_open_accounts'].head()

0     4.0
1    13.0
2     8.0
3    20.0
4    14.0
Name: number_open_accounts, dtype: float64

In [21]:
df['number_credit_lines_12'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: number_credit_lines_12, dtype: float64

In [22]:
df['target'].head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

### Display the unique values of two variables with discrete values

In [24]:
df['target'].unique()

array([0, 1], dtype=int64)

In [25]:
df['number_open_accounts'].unique()

array([ 4., 13.,  8., 20., 14.,  5.,  9., 18., 16., 17., 12., 15.,  6.,
       10., 11.,  7., 21., 19., 26.,  2., 22., 27., 23., 25., 24., 28.,
        3., 30., 41., 32., 33., 31., 29., 37., 49., 34., 35., 38.,  1.,
       36., 42., 47., 40., 44., 43.])

In [26]:
df['number_credit_lines_12'].unique()

array([nan,  2.,  4.,  1.,  0.,  3.,  5.,  6.])

### Display the Month with most of loans issued date

In [27]:
df['date_issued_dt']=pd.to_datetime(df['date_issued'])
df['month']=df['date_issued_dt'].dt.month
df['month'].head()

0     6
1     5
2    10
3     8
4     7
Name: month, dtype: int64

In [29]:
max_val=df['month'].max()
print("Maximum number of loans were issued in the month: ",max_val)

Maximum number of loans were issued in the month:  12


### Display the count of ‘Teacher’ who are ‘Owners’

In [32]:
count=df.loc[(df['employment']=='Teacher') &(df['householder']=='OWNER') ]
print(len(count))

69


### Display the ‘Employment’ of customers who mostly ‘Rent’

In [33]:
emp=df.loc[(df['householder']=='RENT')]
print(emp['employment'])

0                  Teacher
2             Statistician
3                    Other
4               Bus driver
6                Secretary
               ...        
9991    Software developer
9992          Statistician
9994            Accountant
9996         Civil Servant
9998            Bus driver
Name: employment, Length: 4055, dtype: object


In [34]:
print(emp['employment'].unique())

['Teacher' 'Statistician' 'Other' 'Bus driver' 'Secretary'
 'Software developer' 'Nurse' 'Accountant' 'Civil Servant' 'Dentist'
 'Taxi driver' nan]
